package com.interview.mysqlescdc.consumer.rebuild;

import java.time.Duration;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;
import org.apache.kafka.clients.consumer.*;import org.apache.kafka.common.TopicPartition;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Component;
import com.interview.mysqlescdc.consumer.canal.*;import com.interview.mysqlescdc.consumer.projection.*;import com.interview.mysqlescdc.consumer.sink.*;import com.interview.mysqlescdc.consumer.source.*;

@Component public final class KafkaShadowReplayService implements ShadowReplayService {
 private static final int ATTEMPTS=3;private static final Duration READY_TIMEOUT=Duration.ofSeconds(10);
 private final String topic;private final ShadowOffsetStore offsets;private final ShadowConsumerFactory consumers;private final CanalRevisionParser parser;private final SourceSnapshotRepository source;private final SearchDocumentProjector projector;private final ElasticsearchGateway sink;
 private final AtomicBoolean stopRequested=new AtomicBoolean();private volatile ShadowReplayRequest starting,active;private volatile ShadowReplayStatus status;private volatile Consumer<String,String> consumer;private volatile Thread worker;private volatile CompletableFuture<ShadowReplayStatus> readiness;
 public KafkaShadowReplayService(@Value("${pipeline.source-topic:product-search-revisions}")String topic,ShadowOffsetStore offsets,ShadowConsumerFactory consumers,CanalRevisionParser parser,SourceSnapshotRepository source,SearchDocumentProjector projector,ElasticsearchGateway sink){this.topic=topic;this.offsets=offsets;this.consumers=consumers;this.parser=parser;this.source=source;this.projector=projector;this.sink=sink;}
 public ShadowReplayStatus start(ShadowReplayRequest request){validate(request);CompletableFuture<ShadowReplayStatus> ready;synchronized(this){if(starting!=null){if(!starting.equals(request))throw new IllegalStateException("shadow start in progress");ready=readiness;}else{if(active!=null&&status.running()){if(active.equals(request))return status;throw new IllegalStateException(active.runId().equals(request.runId())?"conflicting shadow run":"another shadow run active");}if(worker!=null&&worker.isAlive())throw new IllegalStateException("previous shadow worker terminating");starting=request;stopRequested.set(false);var created=new CompletableFuture<ShadowReplayStatus>();readiness=ready=created;worker=Thread.ofVirtual().name("shadow-replay-"+request.runId()).start(()->run(request,created));}}try{return await(ready);}catch(RuntimeException failure){joinWorker();throw failure;}}
 private ShadowReplayStatus await(CompletableFuture<ShadowReplayStatus> ready){try{return ready.get(READY_TIMEOUT.toMillis(),TimeUnit.MILLISECONDS);}catch(ExecutionException e){if(e.getCause() instanceof RuntimeException runtime)throw runtime;throw new IllegalStateException("shadow readiness failed",e.getCause());}catch(TimeoutException e){throw new IllegalStateException("shadow readiness timeout",e);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("shadow readiness interrupted",e);}}
 private void validate(ShadowReplayRequest r){Objects.requireNonNull(r);if(r.runId()==null||!topic.equals(r.topic())||r.offsets()==null||r.offsets().size()!=3||!r.offsets().keySet().equals(Set.of(0,1,2))||r.offsets().values().stream().anyMatch(v->v==null||v<0))throw new IllegalArgumentException("configured topic and exact partitions 0/1/2 required");ElasticsearchTargets.requireSafe(r.target());}
 private void run(ShadowReplayRequest r,CompletableFuture<ShadowReplayStatus> ready){try(var c=consumers.create(r.runId())){consumer=c;checkStop();var ps=List.of(new TopicPartition(r.topic(),0),new TopicPartition(r.topic(),1),new TopicPartition(r.topic(),2));var beginnings=c.beginningOffsets(ps);var ends=c.endOffsets(ps);requireExact(ps,beginnings,ends);for(var tp:ps){long wanted=r.offsets().get(tp.partition());if(wanted<beginnings.get(tp))throw new RequiredOffsetExpiredException();if(wanted>ends.get(tp))throw new IllegalArgumentException("required offset ahead of end");}c.assign(ps);for(var tp:ps)c.seek(tp,r.offsets().get(tp.partition()));checkStop();offsets.initialize(r.runId(),r.topic(),r.offsets());checkStop();synchronized(this){active=r;starting=null;status=snapshot(r,r.offsets(),true,null);}ready.complete(status);while(!stopRequested.get()){for(var record:c.poll(Duration.ofMillis(200))){settleWithRetry(r,record);advance(r,record.partition(),record.offset()+1);if(stopRequested.get())break;}}}
  catch(org.apache.kafka.common.errors.WakeupException e){if(!stopRequested.get())failure(r,ready,e);}catch(Exception e){failure(r,ready,e);}finally{consumer=null;synchronized(this){if(starting==r)starting=null;if(stopRequested.get()&&status!=null&&r.runId().equals(status.runId())&&status.running())status=snapshot(r,status.nextOffsets(),false,null);}}}
 private static void requireExact(List<TopicPartition> ps,Map<TopicPartition,Long> beginnings,Map<TopicPartition,Long> ends){var exact=Set.copyOf(ps);if(!beginnings.keySet().equals(exact)||!ends.keySet().equals(exact))throw new IllegalArgumentException("exact Kafka partition metadata required");}
 private void checkStop(){if(stopRequested.get())throw new CancellationException("shadow stopped before ready");}
 private void failure(ShadowReplayRequest r,CompletableFuture<ShadowReplayStatus> ready,Exception e){if(!ready.isDone()){synchronized(this){starting=null;active=null;status=null;}ready.completeExceptionally(e);return;}if(!stopRequested.get())status=snapshot(r,status.nextOffsets(),false,e.getClass().getSimpleName());}
 private void settleWithRetry(ShadowReplayRequest r,ConsumerRecord<String,String> record){RuntimeException last=null;for(int n=1;n<=ATTEMPTS;n++){try{settle(r,record);return;}catch(BulkTransportException|BulkProtocolException|RetryableShadowException e){last=e;}if(n<ATTEMPTS)try{Thread.sleep(100L*n);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new RetryableShadowException(e);}}throw last;}
 private void settle(ShadowReplayRequest r,ConsumerRecord<String,String> record){var signals=parser.parse(record.value());if(signals.isEmpty())return;var byId=new TreeMap<Long,RevisionSignal>();for(var s:signals)byId.merge(s.productId(),s,(a,b)->a.eventRevision()>=b.eventRevision()?a:b);var docs=new ArrayList<SearchDocument>();for(var signal:byId.values()){var snapshot=source.load(signal.productId()).orElseThrow(()->new IllegalStateException("missing source"));if(snapshot.revision()<signal.eventRevision())throw new RetryableShadowException("source behind signal");docs.add(projector.project(snapshot));}var result=sink.write(r.target(),docs);if(result.items().size()!=docs.size())throw new RetryableShadowException("bulk count mismatch");if(result.items().stream().anyMatch(i->i.outcome()==BulkOutcome.PERMANENT_FAILURE))throw new IllegalStateException("shadow poison");if(result.items().stream().anyMatch(i->i.outcome()==BulkOutcome.RETRYABLE_FAILURE))throw new RetryableShadowException("retryable bulk item");}
 private synchronized void advance(ShadowReplayRequest r,int partition,long next){offsets.advance(r.runId(),r.topic(),partition,next);var m=new TreeMap<>(status.nextOffsets());m.merge(partition,next,Math::max);status=snapshot(r,m,status.running(),status.failureClass());}
 public ShadowReplayStatus status(UUID runId){var s=status;if(s==null||!runId.equals(s.runId()))throw new ShadowRunNotFoundException();return s;}
 public ShadowReplayStatus stop(UUID runId){Thread w;Consumer<String,String> c;synchronized(this){if(starting!=null&&!runId.equals(starting.runId()))throw new ShadowRunNotFoundException();if(starting==null&&(status==null||!runId.equals(status.runId())))throw new ShadowRunNotFoundException();stopRequested.set(true);c=consumer;w=worker;}if(c!=null)c.wakeup();if(w!=null){w.interrupt();try{w.join(Duration.ofSeconds(5));}catch(InterruptedException e){Thread.currentThread().interrupt();}if(w.isAlive())throw new IllegalStateException("shadow stop timeout");}var s=status;if(s==null)throw new ShadowRunNotFoundException();return s;}
 private void joinWorker(){var w=worker;if(w!=null)try{w.join(Duration.ofSeconds(5));}catch(InterruptedException e){Thread.currentThread().interrupt();}if(w!=null&&w.isAlive())throw new IllegalStateException("shadow readiness cleanup timeout");}
 private static ShadowReplayStatus snapshot(ShadowReplayRequest r,Map<Integer,Long> next,boolean running,String failure){return new ShadowReplayStatus(r.runId(),r.target(),Set.copyOf(r.offsets().keySet()),Map.copyOf(next),running,failure);}
 private static final class RetryableShadowException extends RuntimeException{RetryableShadowException(String m){super(m);}RetryableShadowException(Throwable t){super(t);}}
}
