package com.interview.mysqlescdc.consumer.rebuild;
import static org.assertj.core.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.jdbc.datasource.*;import org.springframework.transaction.support.TransactionTemplate;
class JdbcShadowOffsetStoreIT {
 JdbcClient jdbc;JdbcShadowOffsetStore store;TransactionTemplate tx;UUID run;
 @BeforeEach void setup(){var ds=new DriverManagerDataSource("jdbc:mysql://127.0.0.1:3308/product_catalog?useSSL=false&allowPublicKeyRetrieval=true","root","rootpass");jdbc=JdbcClient.create(ds);store=new JdbcShadowOffsetStore(jdbc);tx=new TransactionTemplate(new DataSourceTransactionManager(ds));run=UUID.randomUUID();jdbc.sql("INSERT INTO rebuild_run(run_id,generation_name,status) VALUES(UUID_TO_BIN(:run),:name,'REPLAYING')").param("run",run.toString()).param("name","products_v3_20260728123456_"+run.toString().substring(0,8)).update();}
 @AfterEach void cleanup(){jdbc.sql("DROP TRIGGER IF EXISTS test_shadow_offset_failure").update();jdbc.sql("DELETE FROM rebuild_partition_offset WHERE run_id=UUID_TO_BIN(:run)").param("run",run.toString()).update();jdbc.sql("DELETE FROM rebuild_run WHERE run_id=UUID_TO_BIN(:run)").param("run",run.toString()).update();}
 @Test void late_partition_collision_rolls_back_all_new_rows(){jdbc.sql("INSERT INTO rebuild_partition_offset(run_id,phase,topic_name,partition_id,next_offset) VALUES(UUID_TO_BIN(:run),'SHADOW','product-search-revisions',2,9)").param("run",run.toString()).update();assertThatThrownBy(()->initialize()).isInstanceOf(RuntimeException.class);assertThat(count()).isEqualTo(1);}
 @Test void forced_database_failure_leaves_zero_partial_rows(){jdbc.sql("CREATE TRIGGER test_shadow_offset_failure BEFORE INSERT ON rebuild_partition_offset FOR EACH ROW BEGIN IF NEW.run_id=UUID_TO_BIN('"+run+"') AND NEW.partition_id=1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced'; END IF; END").update();assertThatThrownBy(()->initialize()).isInstanceOf(RuntimeException.class);assertThat(count()).isZero();}
 private void initialize(){tx.executeWithoutResult(s->store.initialize(run,"product-search-revisions",Map.of(0,7L,1,8L,2,9L)));}
 private long count(){return jdbc.sql("SELECT COUNT(*) FROM rebuild_partition_offset WHERE run_id=UUID_TO_BIN(:run) AND phase='SHADOW'").param("run",run.toString()).query(Long.class).single();}
}
