package com.interview.mysqlescdc.consumer.rebuild;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicInteger;
import org.apache.kafka.clients.consumer.*;import org.apache.kafka.common.TopicPartition;import org.junit.jupiter.api.Test;
import com.interview.mysqlescdc.consumer.canal.CanalRevisionParser;import com.interview.mysqlescdc.consumer.projection.SearchDocumentProjector;import com.interview.mysqlescdc.consumer.sink.*;import com.interview.mysqlescdc.consumer.source.*;import tools.jackson.databind.json.JsonMapper;

class KafkaShadowReplayServiceTest {
 @Test void readiness_precedes_running_and_retry_does_not_advance_until_settled()throws Exception{UUID run=UUID.randomUUID();String topic="product-search-revisions";var tp0=new TopicPartition(topic,0);var ps=List.of(tp0,new TopicPartition(topic,1),new TopicPartition(topic,2));@SuppressWarnings("unchecked") Consumer<String,String> consumer=mock(Consumer.class);var bounds=Map.of(ps.get(0),0L,ps.get(1),0L,ps.get(2),0L);when(consumer.beginningOffsets(ps)).thenReturn(bounds);when(consumer.endOffsets(ps)).thenReturn(bounds);var record=new ConsumerRecord<String,String>(topic,0,0,null,payload());when(consumer.poll(any(Duration.class))).thenReturn(new ConsumerRecords<>(Map.of(tp0,List.of(record))),ConsumerRecords.empty());var store=mock(ShadowOffsetStore.class);var source=mock(SourceSnapshotRepository.class);var behind=SourceProductSnapshot.active(1,"S","N","D",1,"C",1,1,1,Instant.EPOCH);var current=SourceProductSnapshot.active(1,"S","N","D",1,"C",1,1,2,Instant.EPOCH);when(source.load(1)).thenReturn(Optional.of(behind),Optional.of(current),Optional.of(current));var sink=mock(ElasticsearchGateway.class);var second=new CountDownLatch(1);var release=new CountDownLatch(1);var calls=new AtomicInteger();when(sink.write(anyString(),anyList())).thenAnswer(i->{if(calls.incrementAndGet()==1)throw new BulkTransportException("retry");second.countDown();release.await(2,TimeUnit.SECONDS);return new BulkWriteResult(List.of(new BulkItemResult(1,2,BulkOutcome.APPLIED,201,null,null)));});var service=new KafkaShadowReplayService(topic,store,id->consumer,new CanalRevisionParser(JsonMapper.builder().build()),source,new SearchDocumentProjector(),sink);var request=new ShadowReplayRequest(run,topic,"products_v3_20260728123456_deadbeef",Map.of(0,0L,1,0L,2,0L));assertThat(service.start(request).running()).isTrue();verify(store).initialize(run,topic,request.offsets());assertThat(second.await(2,TimeUnit.SECONDS)).isTrue();verify(store,never()).advance(any(),anyString(),anyInt(),anyLong());assertThat(service.status(run).nextOffsets().get(0)).isZero();release.countDown();verify(store,timeout(2000)).advance(run,topic,0,1);verify(source,times(3)).load(1);assertThat(service.stop(run).running()).isFalse();}
 @Test void factory_has_exact_non_committing_configuration(){UUID run=UUID.randomUUID();var p=KafkaShadowConsumerFactory.properties("k:9092",run);assertThat(p.get(ConsumerConfig.GROUP_ID_CONFIG)).isEqualTo("rebuild-shadow-"+run);assertThat(p.get(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG)).isEqualTo("none");assertThat(p.get(ConsumerConfig.ISOLATION_LEVEL_CONFIG)).isEqualTo("read_committed");assertThat(p.get(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG)).isEqualTo("false");}
 @Test void retryable_item_exhaustion_fails_without_advancing_offset()throws Exception{UUID run=UUID.randomUUID();String topic="product-search-revisions";var tp0=new TopicPartition(topic,0);var ps=List.of(tp0,new TopicPartition(topic,1),new TopicPartition(topic,2));@SuppressWarnings("unchecked") Consumer<String,String> consumer=mock(Consumer.class);var bounds=Map.of(ps.get(0),0L,ps.get(1),0L,ps.get(2),0L);when(consumer.beginningOffsets(ps)).thenReturn(bounds);when(consumer.endOffsets(ps)).thenReturn(bounds);when(consumer.poll(any(Duration.class))).thenReturn(new ConsumerRecords<>(Map.of(tp0,List.of(new ConsumerRecord<>(topic,0,0,null,payload())))),ConsumerRecords.empty());var store=mock(ShadowOffsetStore.class);var source=mock(SourceSnapshotRepository.class);when(source.load(1)).thenReturn(Optional.of(SourceProductSnapshot.active(1,"S","N","D",1,"C",1,1,2,Instant.EPOCH)));var sink=mock(ElasticsearchGateway.class);when(sink.write(anyString(),anyList())).thenReturn(new BulkWriteResult(List.of(new BulkItemResult(1,2,BulkOutcome.RETRYABLE_FAILURE,429,null,null))));var service=new KafkaShadowReplayService(topic,store,id->consumer,new CanalRevisionParser(JsonMapper.builder().build()),source,new SearchDocumentProjector(),sink);var request=new ShadowReplayRequest(run,topic,"products_v3_20260728123456_deadbeef",Map.of(0,0L,1,0L,2,0L));service.start(request);verify(sink,timeout(2000).times(3)).write(anyString(),anyList());awaitFailure(service,run);verify(store,never()).advance(any(),anyString(),anyInt(),anyLong());assertThat(service.status(run).nextOffsets().get(0)).isZero();}
 private static void awaitFailure(KafkaShadowReplayService service,UUID run)throws Exception{var deadline=Instant.now().plusSeconds(2);while(Instant.now().isBefore(deadline)&&service.status(run).running())Thread.sleep(20);assertThat(service.status(run).running()).isFalse();}
 private static String payload(){return "{\"database\":\"product_catalog\",\"table\":\"product_search_revision\",\"isDdl\":false,\"id\":1,\"data\":[{\"product_id\":\"1\",\"revision\":\"2\",\"active\":\"1\"}]}";}
}
