package com.interview.mysqlescdc.verifier.rebuild;
import java.net.URI;import java.net.http.*;import java.time.Duration;import java.util.*;import java.util.regex.Pattern;import org.springframework.beans.factory.annotation.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Component;import com.interview.mysqlescdc.verifier.source.*;import tools.jackson.databind.*;import tools.jackson.databind.json.JsonMapper;import tools.jackson.databind.node.ObjectNode;
@Component public final class SnapshotGenerationWriter {
 private static final Pattern TARGET=Pattern.compile("products_v3_[0-9]{14}_[0-9a-f]{8}");private final JdbcClient jdbc;private final HttpClient http;private final JsonMapper json;private final String base;
 @Autowired public SnapshotGenerationWriter(JdbcClient jdbc,@Value("${verification.elasticsearch-url:http://localhost:9200}")String base){this(jdbc,HttpClient.newHttpClient(),JsonMapper.builder().findAndAddModules().build(),base);}
 SnapshotGenerationWriter(JdbcClient jdbc,HttpClient http,JsonMapper json,String base){this.jdbc=jdbc;this.http=http;this.json=json;this.base=base.replaceAll("/+$","");}
 public long write(UUID runId,String generation,SourceSnapshotCursor cursor,int pageSize){if(pageSize<1||pageSize>1000)throw new IllegalArgumentException("pageSize must be 1..1000");Reservation r=jdbc.sql("SELECT generation_name name,status,source_count sourceCount,alias_swapped swapped FROM rebuild_run WHERE run_id=UUID_TO_BIN(:run)").param("run",runId.toString()).query(Reservation.class).single();if(!TARGET.matcher(generation).matches()||!generation.equals(r.name())||!"CREATED".equals(r.status())||r.swapped()||r.sourceCount()!=0)throw new IllegalStateException("exact new reserved generation required");long count=0,cursorId=0;try(cursor){while(true){ExpectedPage page=cursor.readAfter(cursorId,pageSize);if(!page.documents().isEmpty()){bulk(generation,page.documents());long next=count+page.documents().size();int changed=jdbc.sql("UPDATE rebuild_run SET source_count=:next WHERE run_id=UUID_TO_BIN(:run) AND generation_name=:name AND status='CREATED' AND alias_swapped=FALSE AND source_count=:before").param("next",next).param("run",runId.toString()).param("name",generation).param("before",count).update();if(changed!=1)throw new IllegalStateException("source_count settlement lost");count=next;cursorId=page.nextExclusiveProductId();}if(page.complete())return count;}}
 }
 private void bulk(String target,List<ExpectedDocument> docs){StringBuilder body=new StringBuilder();for(var d:docs){var root=json.createObjectNode();var action=root.putObject("index");action.put("_index",target);action.put("_id",Long.toString(d.productId()));action.put("version",d.sourceRevision());action.put("version_type","external");body.append(root).append('\n').append(document(d)).append('\n');}try{var req=HttpRequest.newBuilder(URI.create(base+"/_bulk")).timeout(Duration.ofSeconds(10)).header("Content-Type","application/x-ndjson").POST(HttpRequest.BodyPublishers.ofString(body.toString())).build();var response=http.send(req,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IllegalStateException("snapshot Bulk HTTP failure");JsonNode items=json.readTree(response.body()).path("items");if(!items.isArray()||items.size()!=docs.size())throw new IllegalStateException("snapshot Bulk item count mismatch");for(var item:items){int status=item.path("index").path("status").asInt();if(status<200||status>=300)throw new IllegalStateException("snapshot Bulk item failure");}}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("snapshot Bulk interrupted",e);}catch(java.io.IOException e){throw new IllegalStateException("snapshot Bulk failed",e);}}
 private String document(ExpectedDocument d){ObjectNode n=json.createObjectNode();n.put("product_id",d.productId());if(d.searchable()){n.put("sku",d.sku());n.put("name",d.name());n.put("description",d.description());n.put("category_id",d.categoryId());n.put("category_name",d.categoryName());n.put("price_cents",d.priceCents());n.put("available_quantity",d.availableQuantity());}n.put("searchable",d.searchable());n.put("source_revision",d.sourceRevision());n.put("source_updated_at",d.sourceUpdatedAt().toString());return n.toString();}
 private record Reservation(String name,String status,long sourceCount,boolean swapped){}
}
