package com.interview.mysqlescdc.verifier.rebuild;
import java.net.URI;import java.net.http.*;import java.time.Duration;import java.util.*;import java.util.regex.Pattern;import java.io.InputStream;import org.springframework.beans.factory.annotation.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Component;import com.interview.mysqlescdc.verifier.source.*;import tools.jackson.databind.*;import tools.jackson.databind.json.JsonMapper;import tools.jackson.databind.node.ObjectNode;
@Component public final class SnapshotGenerationWriter {
 private static final Pattern TARGET=Pattern.compile("products_v3_[0-9]{14}_[0-9a-f]{8}");private final JdbcClient jdbc;private final HttpClient http;private final JsonMapper json;private final String base;private final int pageDelayMs;
 @Autowired public SnapshotGenerationWriter(JdbcClient jdbc,@Value("${verification.elasticsearch-url:http://localhost:9200}")String base,@Value("${lab.snapshot-page-delay-ms:0}")int pageDelayMs){this(jdbc,HttpClient.newHttpClient(),JsonMapper.builder().findAndAddModules().build(),base,pageDelayMs);}
 SnapshotGenerationWriter(JdbcClient jdbc,String base){this(jdbc,HttpClient.newHttpClient(),JsonMapper.builder().findAndAddModules().build(),base,0);}
 SnapshotGenerationWriter(JdbcClient jdbc,HttpClient http,JsonMapper json,String base){this(jdbc,http,json,base,0);}
 SnapshotGenerationWriter(JdbcClient jdbc,HttpClient http,JsonMapper json,String base,int pageDelayMs){this.jdbc=jdbc;this.http=http;this.json=json;this.base=base.replaceAll("/+$","");if(pageDelayMs<0||pageDelayMs>10000)throw new IllegalArgumentException("snapshot page delay must be 0..10000ms");this.pageDelayMs=pageDelayMs;}
 public long write(UUID runId,String generation,SourceSnapshotCursor cursor,int pageSize){boolean accepted=false;try(cursor){if(pageSize<1||pageSize>1000)throw new IllegalArgumentException("pageSize must be 1..1000");Reservation r=jdbc.sql("SELECT generation_name name,status,source_count sourceCount,alias_swapped swapped FROM rebuild_run WHERE run_id=UUID_TO_BIN(:run)").param("run",runId.toString()).query(Reservation.class).single();if(!TARGET.matcher(generation).matches()||!generation.equals(r.name())||!"SNAPSHOTTING".equals(r.status())||r.swapped()||r.sourceCount()!=0)throw new IllegalStateException("exact new SNAPSHOTTING generation required");accepted=true;long count=0,cursorId=0;validatePhysical(runId,generation);while(true){ExpectedPage page=cursor.readAfter(cursorId,pageSize);if(!page.documents().isEmpty()){bulk(generation,page.documents());long next=count+page.documents().size();int changed=jdbc.sql("UPDATE rebuild_run SET source_count=:next WHERE run_id=UUID_TO_BIN(:run) AND generation_name=:name AND status='SNAPSHOTTING' AND alias_swapped=FALSE AND source_count=:before").param("next",next).param("run",runId.toString()).param("name",generation).param("before",count).update();if(changed!=1)throw new IllegalStateException("source_count settlement lost");count=next;cursorId=page.nextExclusiveProductId();if(!page.complete())pageDelay();}if(page.complete())return count;}}catch(RuntimeException failure){if(accepted)try{markFailed(runId,generation,failure);}catch(RuntimeException persistence){failure.addSuppressed(persistence);}throw failure;}}
 private void pageDelay(){if(pageDelayMs==0)return;try{Thread.sleep(pageDelayMs);}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw new IllegalStateException("snapshot page delay interrupted",interrupted);}}
 private void markFailed(UUID run,String generation,RuntimeException failure){String message=(failure.getMessage()==null?failure.getClass().getSimpleName():failure.getMessage());if(message.length()>512)message=message.substring(0,512);int changed=jdbc.sql("UPDATE rebuild_run SET status='FAILED',failure_phase='SNAPSHOT',failure_message=:message,finished_at=CURRENT_TIMESTAMP(6) WHERE run_id=UUID_TO_BIN(:run) AND generation_name=:name AND status='SNAPSHOTTING' AND alias_swapped=FALSE").param("message",message).param("run",run.toString()).param("name",generation).update();if(changed!=1)failure.addSuppressed(new IllegalStateException("failed to persist snapshot failure"));}
 private void validatePhysical(UUID run,String generation){JsonNode mappings=parse(response("GET","/"+generation+"/_mapping",null,200)).path(generation).path("mappings");JsonNode meta=mappings.path("_meta");if(!run.toString().equals(meta.path("rebuild_run_id").asText())||meta.path("schema_version").asInt()!=3||!"tombstone".equals(meta.path("deletion_mode").asText())||!validCreatedAt(generation,meta.path("created_at").asText()))throw new IllegalStateException("generation metadata mismatch");try(InputStream in=getClass().getResourceAsStream("/products-v3-template.json")){ObjectNode expected=(ObjectNode)json.readTree(in).path("mappings").deepCopy();((ObjectNode)expected.path("_meta")).put("rebuild_run_id",run.toString()).put("created_at",meta.path("created_at").asText());if(!expected.equals(mappings))throw new IllegalStateException("generation mapping mismatch");}catch(java.io.IOException e){throw new IllegalStateException("cannot validate generation template",e);}JsonNode settings=parse(response("GET","/"+generation+"/_settings",null,200)).path(generation).path("settings").path("index");if(!"1".equals(settings.path("number_of_shards").asText())||!"0".equals(settings.path("number_of_replicas").asText())||!"1s".equals(settings.path("refresh_interval").asText()))throw new IllegalStateException("generation settings mismatch");JsonNode aliases=parse(response("GET","/"+generation,null,200)).path(generation).path("aliases");if(!aliases.isObject()||!aliases.isEmpty())throw new IllegalStateException("generation must be an unaliased physical index");}
 public void refresh(String generation){if(!TARGET.matcher(generation).matches())throw new IllegalArgumentException("unsafe generation target");response("POST","/"+generation+"/_refresh",null,200);}
 private boolean validCreatedAt(String generation,String createdAt){try{var instant=java.time.Instant.parse(createdAt);var stamp=java.time.format.DateTimeFormatter.ofPattern("yyyyMMddHHmmss").withZone(java.time.ZoneOffset.UTC).format(instant);return generation.substring(12,26).equals(stamp);}catch(RuntimeException failure){return false;}}
 private String response(String method,String path,String body,int expected){try{var b=HttpRequest.newBuilder(URI.create(base+path)).timeout(Duration.ofSeconds(10)).header("Content-Type","application/json").method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body));var r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()!=expected)throw new IllegalStateException("generation validation HTTP "+r.statusCode());return r.body();}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("generation validation interrupted",e);}catch(java.io.IOException e){throw new IllegalStateException("generation validation failed",e);}}
 private JsonNode parse(String payload){try{return json.readTree(payload);}catch(Exception e){throw new IllegalStateException("invalid generation JSON",e);}}
 private void bulk(String target,List<ExpectedDocument> docs){
  StringBuilder body=new StringBuilder();
  for(var d:docs){var root=json.createObjectNode();var action=root.putObject("index");action.put("_index",target);action.put("_id",Long.toString(d.productId()));action.put("version",d.sourceRevision());action.put("version_type","external");body.append(root).append('\n').append(document(d)).append('\n');}
  try{
   var req=HttpRequest.newBuilder(URI.create(base+"/_bulk")).timeout(Duration.ofSeconds(10)).header("Content-Type","application/x-ndjson").POST(HttpRequest.BodyPublishers.ofString(body.toString())).build();
   var response=http.send(req,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IllegalStateException("snapshot Bulk HTTP failure");
   JsonNode items=json.readTree(response.body()).path("items");if(!items.isArray()||items.size()!=docs.size())throw new IllegalStateException("snapshot Bulk item count mismatch");
   for(int i=0;i<items.size();i++){var result=items.get(i).path("index");int status=result.path("status").asInt();if(status>=200&&status<300)continue;if(status==409&&settledByShadow(target,docs.get(i)))continue;throw new IllegalStateException("snapshot Bulk item failure: "+result.path("error"));}
  }catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("snapshot Bulk interrupted",e);}catch(java.io.IOException e){throw new IllegalStateException("snapshot Bulk failed",e);}
 }
 private boolean settledByShadow(String target,ExpectedDocument snapshot){JsonNode existing=parse(response("GET","/"+target+"/_doc/"+snapshot.productId(),null,200));long version=existing.path("_version").asLong(-1);if(!existing.path("found").asBoolean())return false;if(version==snapshot.sourceRevision())return existing.path("_source").equals(parse(document(snapshot)));ExpectedDocument current=new JdbcExpectedDocumentReader(jdbc,new IndependentExpectedProjector()).load(snapshot.productId()).orElse(null);return current!=null&&version==current.sourceRevision()&&version>snapshot.sourceRevision()&&existing.path("_source").equals(parse(document(current)));}
 private String document(ExpectedDocument d){ObjectNode n=json.createObjectNode();n.put("product_id",d.productId());if(d.searchable()){n.put("sku",d.sku());n.put("name",d.name());n.put("description",d.description());n.put("category_id",d.categoryId());n.put("category_name",d.categoryName());n.put("price_cents",d.priceCents());n.put("available_quantity",d.availableQuantity());}n.put("searchable",d.searchable());n.put("source_revision",d.sourceRevision());n.put("source_updated_at",d.sourceUpdatedAt().toString());return n.toString();}
 private record Reservation(String name,String status,long sourceCount,boolean swapped){}
}
