package com.interview.mysqlescdc.verifier.rebuild;
import static org.assertj.core.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.jdbc.datasource.DriverManagerDataSource;import com.interview.mysqlescdc.verifier.source.*;
class JdbcConsistentSourceScannerIT {
 static final long BASE=981000;JdbcClient root;JdbcConsistentSourceScanner scanner;
 @BeforeEach void setup(){root=JdbcClient.create(new DriverManagerDataSource(url(),"root","rootpass"));scanner=new JdbcConsistentSourceScanner(new DriverManagerDataSource(url(),"verifier","verifierpass"),new IndependentExpectedProjector());cleanup();root.sql("INSERT INTO categories(id,name) VALUES(:id,'Original category')").param("id",BASE).update();for(int i=1;i<=4;i++){long id=BASE+i;root.sql("INSERT INTO products(id,sku,name,description,category_id,price_cents,status) VALUES(:id,:sku,:name,'d',:category,100,'ACTIVE')").param("id",id).param("sku","SNAP-"+id).param("name","Original "+i).param("category",BASE).update();root.sql("INSERT INTO inventory(product_id,available_quantity,reserved_quantity) VALUES(:id,5,0)").param("id",id).update();root.sql("INSERT INTO product_search_revision(product_id,revision,active,updated_at) VALUES(:id,1,TRUE,'2026-07-28 10:00:00.123456')").param("id",id).update();}}
 @AfterEach void cleanup(){root.sql("DELETE FROM product_search_revision WHERE product_id BETWEEN :a AND :b").param("a",BASE).param("b",BASE+10).update();root.sql("DELETE FROM inventory WHERE product_id BETWEEN :a AND :b").param("a",BASE).param("b",BASE+10).update();root.sql("DELETE FROM products WHERE id BETWEEN :a AND :b").param("a",BASE).param("b",BASE+10).update();root.sql("DELETE FROM categories WHERE id=:id").param("id",BASE).update();}
 @Test void one_connection_repeatable_read_snapshot_excludes_concurrent_changes(){Map<Long,ExpectedDocument> observed=new LinkedHashMap<>();try(var cursor=scanner.open()){long after=0;boolean mutated=false;while(true){var page=cursor.readAfter(after,2);page.documents().forEach(d->{if(d.productId()>BASE&&d.productId()<=BASE+10)observed.put(d.productId(),d);});if(!mutated&&observed.keySet().stream().anyMatch(id->id==BASE+1)){mutate();mutated=true;}if(page.complete())break;after=page.nextExclusiveProductId();}}assertThat(observed.keySet()).contains(BASE+1,BASE+2,BASE+3,BASE+4).doesNotContain(BASE+5);assertThat(observed.get(BASE+1).name()).isEqualTo("Original 1");assertThat(observed.get(BASE+1).sourceRevision()).isEqualTo(1);assertThat(observed.get(BASE+2).searchable()).isTrue();try(var fresh=scanner.open()){Map<Long,ExpectedDocument> now=scan(fresh);assertThat(now.get(BASE+1).name()).isEqualTo("Renamed");assertThat(now.get(BASE+1).sourceRevision()).isEqualTo(2);assertThat(now.get(BASE+2).searchable()).isFalse();assertThat(now).containsKey(BASE+5);}}
 private void mutate(){root.sql("UPDATE products SET name='Renamed' WHERE id=:id").param("id",BASE+1).update();root.sql("UPDATE product_search_revision SET revision=2,updated_at='2026-07-28 10:01:00.654321' WHERE product_id=:id").param("id",BASE+1).update();root.sql("UPDATE product_search_revision SET revision=2,active=FALSE WHERE product_id=:id").param("id",BASE+2).update();long id=BASE+5;root.sql("INSERT INTO products(id,sku,name,description,category_id,price_cents,status) VALUES(:id,:sku,'New','d',:category,100,'ACTIVE')").param("id",id).param("sku","SNAP-"+id).param("category",BASE).update();root.sql("INSERT INTO inventory(product_id,available_quantity,reserved_quantity) VALUES(:id,5,0)").param("id",id).update();root.sql("INSERT INTO product_search_revision(product_id,revision,active) VALUES(:id,1,TRUE)").param("id",id).update();}
 private Map<Long,ExpectedDocument> scan(SourceSnapshotCursor c){Map<Long,ExpectedDocument> out=new HashMap<>();long after=0;while(true){var p=c.readAfter(after,200);p.documents().forEach(d->{if(d.productId()>BASE&&d.productId()<=BASE+10)out.put(d.productId(),d);});if(p.complete())return out;after=p.nextExclusiveProductId();}}
 private static String url(){return "jdbc:mysql://127.0.0.1:3308/product_catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC";}
}
