package com.interview.mysqlescdc.verifier.rebuild;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;

class RebuildCoordinatorTest {
    @Test void happy_path_has_exact_phase_before_side_effect_order(){var calls=new ArrayList<String>();var run=UUID.randomUUID();var coordinator=new RebuildCoordinator(new FakeStore(calls,run),new FakeWorkflow(calls),new RebuildFailpointRegistry(true));coordinator.start(new RebuildRequest(run,"MANUAL","product-search-revisions",200));assertThat(calls).containsExactly("persist CREATED","capture O_start","create generation","persist SNAPSHOTTING","open snapshot","start shadow","scan snapshot","close snapshot","persist REPLAYING","assert retained","persist GATING","close gate","publish barrier","observe barrier","await primary","await shadow","pause primary","persist VERIFYING","verify physical","eligibility","persist CUTTING_OVER","cutover","persist CUTOVER_COMMITTED","stop shadow","resume primary","clear LOG_GAP","open gate","persist COMPLETED");}
    @Test void pre_cutover_failure_preserves_primary_and_suppresses_cleanup_errors(){var calls=new ArrayList<String>();var run=UUID.randomUUID();var workflow=new FakeWorkflow(calls);workflow.fail="verify physical";workflow.cleanupFails=true;var coordinator=new RebuildCoordinator(new FakeStore(calls,run),workflow,new RebuildFailpointRegistry(true));assertThatThrownBy(()->coordinator.start(new RebuildRequest(run,"MANUAL","product-search-revisions",200))).hasMessageContaining("verify physical").satisfies(e->assertThat(e.getSuppressed()).hasSize(3));assertThat(calls).doesNotContain("cutover").containsSubsequence("stop shadow","resume primary","open gate","persist FAILED");}
    @Test void after_cutover_failpoint_leaves_durable_boundary_for_forward_recovery(){var calls=new ArrayList<String>();var run=UUID.randomUUID();var store=new FakeStore(calls,run);var flow=new FakeWorkflow(calls);var failpoints=new RebuildFailpointRegistry(true);failpoints.set(RebuildFailpoint.AFTER_ALIAS_SWITCH_BEFORE_GATE_OPEN);var coordinator=new RebuildCoordinator(store,flow,failpoints);assertThatThrownBy(()->coordinator.start(new RebuildRequest(run,"MANUAL","product-search-revisions",200))).hasMessageContaining("AFTER_ALIAS_SWITCH");assertThat(store.status).isEqualTo("CUTOVER_COMMITTED");assertThat(calls).doesNotContain("persist FAILED","open gate");failpoints.clear();flow.topology=RebuildCoordinator.AliasTopology.NEW;coordinator.resume(run);assertThat(calls).containsSubsequence("verify physical","stop shadow","resume primary","clear LOG_GAP","open gate","persist COMPLETED");}
    @Test void contradictory_startup_truth_keeps_gate_closed_and_activates_rebuild_required(){var calls=new ArrayList<String>();var run=UUID.randomUUID();var store=new FakeStore(calls,run);store.status="CUTOVER_COMMITTED";store.swapped=true;var flow=new FakeWorkflow(calls);flow.topology=RebuildCoordinator.AliasTopology.CONTRADICTORY;var coordinator=new RebuildCoordinator(store,flow,new RebuildFailpointRegistry(true));assertThatThrownBy(()->coordinator.resume(run)).hasMessageContaining("contradicts");assertThat(calls).containsExactly("close gate","activate REBUILD_REQUIRED").doesNotContain("open gate");}
    @Test void every_pre_cutover_side_effect_failure_never_moves_aliases_and_attempts_cleanup(){for(String failed:List.of("capture O_start","create generation","open snapshot","start shadow","scan snapshot","close snapshot","assert retained","close gate","publish barrier","observe barrier","await primary","await shadow","pause primary","verify physical","eligibility")){var calls=new ArrayList<String>();var run=UUID.randomUUID();var flow=new FakeWorkflow(calls);flow.fail=failed;var store=new FakeStore(calls,run);var coordinator=new RebuildCoordinator(store,flow,new RebuildFailpointRegistry(true));assertThatThrownBy(()->coordinator.start(new RebuildRequest(run,"MANUAL","product-search-revisions",200))).isInstanceOf(IllegalStateException.class);assertThat(calls).doesNotContain("cutover").containsSubsequence("stop shadow","resume primary","open gate","persist FAILED");assertThat(store.status).isEqualTo("FAILED");}}
    @Test void aliases_moved_but_cutover_call_failed_is_classified_from_actual_topology(){var calls=new ArrayList<String>();var run=UUID.randomUUID();var flow=new FakeWorkflow(calls);flow.fail="cutover";flow.topology=RebuildCoordinator.AliasTopology.NEW;var store=new FakeStore(calls,run);var coordinator=new RebuildCoordinator(store,flow,new RebuildFailpointRegistry(true));assertThatThrownBy(()->coordinator.start(new RebuildRequest(run,"MANUAL","product-search-revisions",200))).hasMessageContaining("cutover");assertThat(store.status).isEqualTo("CUTOVER_COMMITTED");assertThat(calls).contains("persist CUTOVER_COMMITTED").doesNotContain("persist FAILED","open gate");}
    @Test void startup_during_external_canal_recovery_keeps_owned_gate_closed_and_waits(){var calls=new ArrayList<String>();var run=UUID.randomUUID();var store=new FakeStore(calls,run);store.status="CANAL_RECOVERING";var coordinator=new RebuildCoordinator(store,new FakeWorkflow(calls),new RebuildFailpointRegistry(true));assertThat(coordinator.resume(run).status()).isEqualTo("CANAL_RECOVERING");assertThat(calls).containsExactly("close gate").doesNotContain("persist FAILED","open gate");}
    private static final class FakeStore implements RebuildRunStore{private final List<String> c;private final UUID run;String status="CREATED";boolean swapped;FakeStore(List<String> c,UUID run){this.c=c;this.run=run;}public void create(RebuildRequest r){status="CREATED";c.add("persist CREATED");}public void transition(UUID id,String expected,String next){assertThat(status).isEqualTo(expected);status=next;if("CUTOVER_COMMITTED".equals(next))swapped=true;c.add("persist "+next);}public void fail(UUID id,Throwable failure){status="FAILED";c.add("persist FAILED");}public RebuildStatus get(UUID id){return new RebuildStatus(run,status,"generation",null,swapped);} }
    private static final class FakeWorkflow implements RebuildCoordinator.Workflow{private final List<String> c;String fail;boolean cleanupFails;RebuildCoordinator.AliasTopology topology=RebuildCoordinator.AliasTopology.OLD;FakeWorkflow(List<String> c){this.c=c;}private void x(String s){c.add(s);if(s.equals(fail))throw new IllegalStateException(s);}public void captureStart(UUID r){x("capture O_start");}public void createGeneration(UUID r){x("create generation");}public void openSnapshot(UUID r){x("open snapshot");}public void startShadow(UUID r){x("start shadow");}public void scanSnapshot(UUID r){x("scan snapshot");}public void closeSnapshot(UUID r){x("close snapshot");}public void assertRetained(UUID r){x("assert retained");}public void closeGate(UUID r){x("close gate");}public void publishBarrier(UUID r){x("publish barrier");}public void observeBarrier(UUID r){x("observe barrier");}public void awaitPrimary(UUID r){x("await primary");}public void awaitShadow(UUID r){x("await shadow");}public void pausePrimary(UUID r){x("pause primary");}public void verifyPhysical(UUID r){x("verify physical");}public void requireEligible(UUID r){x("eligibility");}public void cutover(UUID r){x("cutover");}public void stopShadow(UUID r){c.add("stop shadow");if(cleanupFails)throw new IllegalStateException("stop");}public void resumePrimary(UUID r){c.add("resume primary");if(cleanupFails)throw new IllegalStateException("resume");}public void clearLogGap(UUID r){x("clear LOG_GAP");}public void openGate(UUID r){c.add("open gate");if(cleanupFails)throw new IllegalStateException("gate");}public RebuildCoordinator.AliasTopology aliasTopology(UUID r){return topology;}public void activateRebuildRequired(UUID r){x("activate REBUILD_REQUIRED");}}
}
