package com.interview.mysqlescdc.verifier.rebuild;
import static org.assertj.core.api.Assertions.*;import java.net.*;import java.net.http.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.jdbc.datasource.DriverManagerDataSource;import com.interview.mysqlescdc.verifier.source.IndependentExpectedProjector;import tools.jackson.databind.json.JsonMapper;
class SnapshotGenerationWriterIT {
 static final long CATEGORY=982000,ACTIVE=982001,INACTIVE=982002;JdbcClient root,verifier;HttpClient http=HttpClient.newHttpClient();String index;UUID run;
 @BeforeEach void setup(){root=JdbcClient.create(new DriverManagerDataSource(url(),"root","rootpass"));verifier=JdbcClient.create(new DriverManagerDataSource(url(),"verifier","verifierpass"));cleanupRows();root.sql("INSERT INTO categories(id,name) VALUES(:id,'Writer')").param("id",CATEGORY).update();insert(ACTIVE,"ACTIVE",7,true);insert(INACTIVE,"DELETED",9,false);}
 @AfterEach void cleanup()throws Exception{if(index!=null)request("DELETE","/"+index,null,200,404);if(run!=null){root.sql("DELETE FROM rebuild_partition_offset WHERE run_id=UUID_TO_BIN(:run)").param("run",run.toString()).update();root.sql("DELETE FROM rebuild_run WHERE run_id=UUID_TO_BIN(:run)").param("run",run.toString()).update();}cleanupRows();}
 @Test void real_es_contains_every_revision_with_exact_active_tombstone_and_external_version()throws Exception{run=UUID.randomUUID();var generation=new RestGenerationManager(verifier,"http://127.0.0.1:9200").create(run);index=generation.name();var scanner=new JdbcConsistentSourceScanner(new DriverManagerDataSource(url(),"verifier","verifierpass"),new IndependentExpectedProjector());long count=new SnapshotGenerationWriter(verifier,"http://127.0.0.1:9200").write(run,index,scanner.open(),200);long expected=root.sql("SELECT COUNT(*) FROM product_search_revision").query(Long.class).single();assertThat(count).isEqualTo(expected);assertThat(root.sql("SELECT source_count FROM rebuild_run WHERE run_id=UUID_TO_BIN(:run)").param("run",run.toString()).query(Long.class).single()).isEqualTo(expected);var json=JsonMapper.builder().build();var active=json.readTree(request("GET","/"+index+"/_doc/"+ACTIVE,null,200));assertThat(active.path("_version").asLong()).isEqualTo(7);assertThat(active.path("_source").path("searchable").asBoolean()).isTrue();assertThat(active.path("_source").path("name").asText()).isEqualTo("Product "+ACTIVE);var tomb=json.readTree(request("GET","/"+index+"/_doc/"+INACTIVE,null,200));assertThat(tomb.path("_version").asLong()).isEqualTo(9);assertThat(tomb.path("_source").properties().stream().map(Map.Entry::getKey).toList()).containsExactlyInAnyOrder("product_id","searchable","source_revision","source_updated_at");assertThat(tomb.path("_source").path("searchable").asBoolean()).isFalse();}
 @Test void real_bulk_item_failure_keeps_count_at_last_fully_settled_page()throws Exception{run=UUID.randomUUID();var generation=new RestGenerationManager(verifier,"http://127.0.0.1:9200").create(run);index=generation.name();request("PUT","/"+index+"/_doc/"+ACTIVE+"?version=999&version_type=external","{\"product_id\":"+ACTIVE+",\"searchable\":true,\"source_revision\":999,\"source_updated_at\":\"2026-07-28T00:00:00Z\"}",201);var scanner=new JdbcConsistentSourceScanner(new DriverManagerDataSource(url(),"verifier","verifierpass"),new IndependentExpectedProjector());assertThatThrownBy(()->new SnapshotGenerationWriter(verifier,"http://127.0.0.1:9200").write(run,index,scanner.open(),1000)).isInstanceOf(IllegalStateException.class).hasMessageContaining("item failure");long settled=root.sql("SELECT source_count FROM rebuild_run WHERE run_id=UUID_TO_BIN(:run)").param("run",run.toString()).query(Long.class).single();long total=root.sql("SELECT COUNT(*) FROM product_search_revision").query(Long.class).single();assertThat(settled).isLessThan(total);}
 private void insert(long id,String status,long revision,boolean active){root.sql("INSERT INTO products(id,sku,name,description,category_id,price_cents,status) VALUES(:id,:sku,:name,'d',:category,100,:status)").param("id",id).param("sku","WRITE-"+id).param("name","Product "+id).param("category",CATEGORY).param("status",status).update();root.sql("INSERT INTO inventory(product_id,available_quantity,reserved_quantity) VALUES(:id,5,0)").param("id",id).update();root.sql("INSERT INTO product_search_revision(product_id,revision,active,updated_at) VALUES(:id,:revision,:active,'2026-07-28 11:00:00.123456')").param("id",id).param("revision",revision).param("active",active).update();}
 private void cleanupRows(){root.sql("DELETE FROM product_search_revision WHERE product_id IN (:a,:b)").param("a",ACTIVE).param("b",INACTIVE).update();root.sql("DELETE FROM inventory WHERE product_id IN (:a,:b)").param("a",ACTIVE).param("b",INACTIVE).update();root.sql("DELETE FROM products WHERE id IN (:a,:b)").param("a",ACTIVE).param("b",INACTIVE).update();root.sql("DELETE FROM categories WHERE id=:id").param("id",CATEGORY).update();}
 private String request(String method,String path,String body,int...expected)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:9200"+path));if("GET".equals(method))b.GET();else if("DELETE".equals(method))b.DELETE();else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(body));var r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(Arrays.stream(expected).noneMatch(x->x==r.statusCode()))throw new AssertionError(r.statusCode()+" "+r.body());return r.body();}
 private static String url(){return "jdbc:mysql://127.0.0.1:3308/product_catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC";}
}
