canal.instance.mysql.slaveId=1234
canal.instance.gtidon=true
canal.instance.master.address=toxiproxy:8668
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=
canal.instance.dbUsername=canal
canal.instance.dbPassword=canalpass
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false
canal.instance.filter.regex=product_catalog\\.(product_search_revision|cdc_barrier)
canal.instance.filter.black.regex=
canal.instance.tsdb.enable=true
canal.mq.topic=product-search-revisions
canal.mq.partition=0
canal.mq.partitionsNum=3
canal.mq.database.hash=false
canal.mq.partitionHash=product_catalog.product_search_revision:product_id,product_catalog.cdc_barrier:partition_token
