canal.instance.mysql.slaveId=1235
canal.instance.gtidon=true
canal.instance.master.address=mysql:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=
canal.instance.dbUsername=canal
canal.instance.dbPassword=canalpass
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false
canal.instance.filter.regex=product_catalog\\.products
canal.instance.filter.black.regex=
canal.instance.tsdb.enable=true
