services:
  mysql:
    image: mysql:8.0
    container_name: perfshop-p0-mysql
    environment:
      MYSQL_ROOT_PASSWORD: perfshop123
      MYSQL_DATABASE: perfshop
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pperfshop123"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7.4-alpine
    container_name: perfshop-p0-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  downstream:
    build: ./downstream
    container_name: perfshop-p0-downstream
    environment:
      DOWNSTREAM_PORT: "8081"
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8081/health', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: ./app
    container_name: perfshop-p0-app
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: perfshop123
      DB_NAME: perfshop
      APP_PORT: "8080"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_SOCKET_TIMEOUT_SECONDS: "0.25"
      DOWNSTREAM_URL: http://downstream:8081
      DOWNSTREAM_TIMEOUT_SECONDS: "0.35"
      DOWNSTREAM_RETRY_ATTEMPTS: "2"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      downstream:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: perfshop-p0-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app
      - downstream

  grafana:
    image: grafana/grafana:10.4.0
    container_name: perfshop-p0-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
