services:
  mysql:
    image: mysql:8.0
    container_name: perfshop-p0-mysql
    environment:
      MYSQL_ROOT_PASSWORD: perfshop123
      MYSQL_DATABASE: perfshop
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pperfshop123"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: ./app
    container_name: perfshop-p0-app
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: perfshop123
      DB_NAME: perfshop
      APP_PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: perfshop-p0-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app

  grafana:
    image: grafana/grafana:10.4.0
    container_name: perfshop-p0-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

