#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
action="${1:-}";target="${2:-}";require_action "$action";state_dir="${SCENARIO_STATE_DIR:?SCENARIO_STATE_DIR required}";mkdir -p "$state_dir"
guarded=false;guard_command=();if test "$action" = apply && (( $# > 2 ));then guarded=true;guard_command=("${@:3}");trap 'exit 130' INT;trap 'exit 143' TERM;trap '"$0" remove "$target" >/dev/null' EXIT;fi
kafka_state="$state_dir/kafka-retention.json";mysql_state="$state_dir/mysql-retention.json";topic=product-search-revisions
kafka(){ "${compose[@]}" exec -T kafka "/opt/kafka/bin/$1" "${@:2}"; }
mysqlq(){ "${compose[@]}" exec -T -e "MYSQL_PWD=${MYSQL_PWD:?MYSQL_PWD required}" mysql mysql -N -B -u"${MYSQL_USER:-root}" "${@:1}"; }
kafka_status(){ local beginning end committed;beginning="$(kafka kafka-get-offsets.sh --bootstrap-server kafka:9092 --topic "$topic" --time -2|awk -F: 'BEGIN{printf "{"}{printf "%s\"%s\":%s",s,$2,$3;s=","}END{print "}"}')";end="$(kafka kafka-get-offsets.sh --bootstrap-server kafka:9092 --topic "$topic" --time -1|awk -F: 'BEGIN{printf "{"}{printf "%s\"%s\":%s",s,$2,$3;s=","}END{print "}"}')";committed="$(kafka kafka-consumer-groups.sh --bootstrap-server kafka:9092 --group product-search-sync-v1 --describe 2>/dev/null|awk 'BEGIN{printf "{"}$2=="product-search-revisions"{printf "%s\"%s\":%s",s,$3,$4;s=","}END{print "}"}')";jq -n --argjson beginning "$beginning" --argjson end "$end" --argjson committed "$committed" '{target:"kafka",beginning:$beginning,end:$end,committed:$committed,gap:any($beginning|to_entries[];.value>($committed[.key]//0))}';}
case "$target:$action" in
 kafka:apply) test -f "$kafka_state"||{ described="$(kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --describe)";jq -n --arg retention "$(sed -n 's/.*retention.ms=\([^, ]*\).*/\1/p'<<<"$described")" --arg segment_ms "$(sed -n 's/.*segment.ms=\([^, ]*\).*/\1/p'<<<"$described")" --arg segment_bytes "$(sed -n 's/.*segment.bytes=\([^, ]*\).*/\1/p'<<<"$described")" '{"retention.ms":($retention|select(length>0)//"DEFAULT"),"segment.ms":($segment_ms|select(length>0)//"DEFAULT"),"segment.bytes":($segment_bytes|select(length>0)//"DEFAULT")}'|atomic_json "$kafka_state";};register_cleanup "SCENARIO_STATE_DIR='$state_dir' bash scenarios/scripts/fault-retention.sh remove kafka";kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --alter --add-config retention.ms=100,segment.ms=100,segment.bytes=1048576 >/dev/null;kafka_status;;
 kafka:remove) if test -f "$kafka_state";then for key in retention.ms segment.ms segment.bytes;do previous="$(jq -r --arg key "$key" '.[$key]' "$kafka_state")";if test "$previous" = DEFAULT;then kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --alter --delete-config "$key" >/dev/null 2>&1||true;else kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --alter --add-config "$key=$previous" >/dev/null;fi;done;fi;kafka_status;;
 kafka:status) kafka_status;;
 mysql:apply) test -f "$mysql_state"||{ previous="$(mysqlq -e 'SELECT @@GLOBAL.binlog_expire_logs_seconds')";current="$(mysqlq -e 'SHOW BINARY LOG STATUS'|awk '{print $1}')";logs="$(mysqlq -e 'SHOW BINARY LOGS'|awk '{print $1}'|jq -Rsc 'split("\n")|map(select(length>0))')";jq -n --argjson previous "$previous" --arg current "$current" --argjson logs "$logs" '{previous:$previous,recorded_file:$current,pre_files:$logs}'|atomic_json "$mysql_state";};register_cleanup "SCENARIO_STATE_DIR='$state_dir' bash scenarios/scripts/fault-retention.sh remove mysql";mysqlq -e 'SET GLOBAL binlog_expire_logs_seconds=1' >/dev/null;if test "${M6_RETENTION_ADVANCE:-false}" = true;then mysqlq -e 'FLUSH BINARY LOGS; PURGE BINARY LOGS BEFORE NOW();' >/dev/null;fi;"$0" status mysql;;
 mysql:remove) if test -f "$mysql_state";then previous="$(jq -r .previous "$mysql_state")";mysqlq -e "SET GLOBAL binlog_expire_logs_seconds=$previous" >/dev/null;fi;"$0" status mysql;;
 mysql:status) current="$(mysqlq -e 'SHOW BINARY LOG STATUS'|awk '{print $1}')";logs="$(mysqlq -e 'SHOW BINARY LOGS'|awk '{print $1}'|jq -Rsc 'split("\n")|map(select(length>0))')";expire="$(mysqlq -e 'SELECT @@GLOBAL.binlog_expire_logs_seconds')";recorded=null;test ! -f "$mysql_state"||recorded="$(jq -r .recorded_file "$mysql_state")";jq -n --arg current "$current" --argjson files "$logs" --argjson expire "$expire" --arg recorded "$recorded" '{target:"mysql",current_file:$current,files:$files,expire_seconds:$expire,recorded_file:$recorded,recorded_present:($files|index($recorded)!=null)}';;
 *) echo 'target must be kafka or mysql' >&2;exit 64;;esac
if $guarded;then "${guard_command[@]}";fi
