#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
action="${1:-}";target="${2:-}";require_action "$action";state_dir="${SCENARIO_STATE_DIR:?SCENARIO_STATE_DIR required}";export SCENARIO_STATE_DIR
kafka_state="$state_dir/kafka-retention.json";mysql_state="$state_dir/mysql-retention.json";topic=product-search-revisions
destructive_guard(){
 test "${M6_RETENTION_DESTRUCTIVE_ACK:-}" = I_UNDERSTAND_M6_DEDICATED_RETENTION_DESTROYS_LOGS||{ echo 'destructive retention ACK required' >&2;return 64;}
 case "${COMPOSE_PROJECT_NAME:-}" in mysql-es-cdc-handson-m6-?*) ;;*) echo 'dedicated M6 Compose project required' >&2;return 64;;esac
 marker="${SCENARIO_PROVENANCE_FILE:-}";test -f "$marker"&&jq -e --arg project "$COMPOSE_PROJECT_NAME" '.purpose=="m6-dedicated-retention" and .compose_project==$project' "$marker" >/dev/null||{ echo 'matching dedicated-project provenance required' >&2;return 64;}
 for service in mysql kafka;do id="$("${compose[@]}" ps -q "$service")";test -n "$id"||{ echo "dedicated $service container required" >&2;return 64;};label="$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' "$id")";test "$label" = "$COMPOSE_PROJECT_NAME"||{ echo "dedicated $service label mismatch" >&2;return 64;};done
}
if test "$action" = apply;then destructive_guard;fi
mkdir -p "$state_dir"
kafka(){ "${compose[@]}" exec -T kafka "/opt/kafka/bin/$1" "${@:2}"; }
mysqlq(){ "${compose[@]}" exec -T -e "MYSQL_PWD=${MYSQL_PWD:?MYSQL_PWD required}" mysql mysql -N -B -u"${MYSQL_USER:-root}" "${@:1}"; }
offset_map(){ local when="$1";kafka kafka-get-offsets.sh --bootstrap-server kafka:9092 --topic "$topic" --time "$when"|awk -F: 'BEGIN{printf "{"}{printf "%s\"%s\":%s",s,$2,$3;s=","}END{print "}"}'; }
committed_map(){ kafka kafka-consumer-groups.sh --bootstrap-server kafka:9092 --group product-search-sync-v1 --describe 2>/dev/null|awk 'BEGIN{printf "{"}$2=="product-search-revisions"&&$4~/^[0-9]+$/{printf "%s\"%s\":%s",s,$3,$4;s=","}END{print "}"}'; }
kafka_status(){ local beginning end committed captured=null partition=null;beginning="$(offset_map -2)";end="$(offset_map -1)";committed="$(committed_map)";if test -f "$kafka_state";then captured="$(jq -c '.captured_committed//null' "$kafka_state")";partition="$(jq -c '.partition//null' "$kafka_state")";fi;jq -n --argjson beginning "$beginning" --argjson end "$end" --argjson committed "$committed" --argjson captured "$captured" --argjson partition "$partition" '{target:"kafka",beginning:$beginning,end:$end,committed:$committed,captured_committed:$captured,selected_partition:$partition,gap:(if $partition!=null then $beginning[($partition|tostring)]>$captured else any($beginning|to_entries[];.value>($committed[.key]//2147483647)) end)}'; }
kafka_config(){ local described;described="$(kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --describe)";jq -n --arg retention "$(sed -n 's/.*retention.ms=\([^, ]*\).*/\1/p'<<<"$described")" --arg segment_ms "$(sed -n 's/.*segment.ms=\([^, ]*\).*/\1/p'<<<"$described")" --arg segment_bytes "$(sed -n 's/.*segment.bytes=\([^, ]*\).*/\1/p'<<<"$described")" '{"retention.ms":($retention|select(length>0)//"DEFAULT"),"segment.ms":($segment_ms|select(length>0)//"DEFAULT"),"segment.bytes":($segment_bytes|select(length>0)//"DEFAULT")}'; }
restore_kafka(){ test -f "$kafka_state"||return 0;for key in retention.ms segment.ms segment.bytes;do previous="$(jq -r --arg key "$key" '.config_before[$key]' "$kafka_state")";if test "$previous" = DEFAULT;then kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --alter --delete-config "$key" >/dev/null 2>&1||true;else kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --alter --add-config "$key=$previous" >/dev/null;fi;done; }
start_consumer(){ "${compose[@]}" --profile m0-tools start search-sync-consumer >/dev/null 2>&1||true; }
failure_kafka(){ restore_kafka;start_consumer; }
restore_mysql(){ test -f "$mysql_state"||return 0;previous="$(jq -r .expire_before "$mysql_state")";mysqlq -e "SET GLOBAL binlog_expire_logs_seconds=$previous" >/dev/null; }
signal_restore(){ local code="$1";trap - EXIT INT TERM;case "$target" in kafka) restore_kafka;;mysql) restore_mysql;;esac;exit "$code"; }
case "$target:$action" in
 kafka:apply)
  before="$(kafka_status)";partition="$(jq -r '[.committed|to_entries[]|select(.value>=0)][0].key//empty'<<<"$before")";test -n "$partition"||{ echo 'no valid committed partition for deterministic Kafka gap' >&2;exit 1;};captured="$(jq -r --arg p "$partition" '.committed[$p]'<<<"$before")";config="$(kafka_config)"
  jq -n --argjson config "$config" --argjson before "$before" --argjson partition "$partition" --argjson captured "$captured" '{config_before:$config,before:$before,partition:$partition,captured_committed:$captured,consumer_stopped:true,action:"captured"}'|atomic_json "$kafka_state";register_cleanup "bash scenarios/scripts/fault-retention.sh remove kafka";"${compose[@]}" stop search-sync-consumer >/dev/null;trap 'failure_kafka' EXIT;trap 'failure_kafka;exit 130' INT;trap 'failure_kafka;exit 143' TERM
  kafka kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name "$topic" --alter --add-config retention.ms=100,segment.ms=100,segment.bytes=1048576 >/dev/null
  last=;for revision in 1 2 3 4 5 6 7 8;do payload="$(jq -cn --arg revision "$revision" '{database:"product_catalog",table:"product_search_revision",isDdl:false,type:"UPDATE",data:[{product_id:"900001",revision:$revision,active:"1"}]}')";request="$(jq -cn --argjson partition "$partition" --arg payload "$payload" '{topic:"product-search-revisions",partition:$partition,payload:$payload}')";last="$("${compose[@]}" exec -T consistency-verifier curl --fail-with-body --silent --show-error --max-time 10 -X POST http://127.0.0.1:8083/internal/lab/scenario-events -H 'Content-Type: application/json' -d "$request"|jq -er .offset)";done
  delete_file="$(mktemp)";trap 'rm -f "$delete_file";restore_kafka' EXIT;delete_to="$last";jq -n --arg topic "$topic" --argjson partition "$partition" --argjson offset "$delete_to" '{partitions:[{topic:$topic,partition:$partition,offset:$offset}],version:1}' >"$delete_file";kafka kafka-delete-records.sh --bootstrap-server kafka:9092 --offset-json-file /dev/stdin <"$delete_file" >/dev/null
  "$wait_condition" 'Kafka beginning offset exceeds captured commit' 60 0.2 bash -c 'SCENARIO_STATE_DIR="$1" "$2" status kafka|jq -e --arg p "$3" --argjson captured "$4" ".beginning[\$p]>\$captured" >/dev/null' _ "$state_dir" "$0" "$partition" "$captured"
  after="$(kafka_status)";jq --argjson after "$after" --argjson delete_to "$delete_to" '.after=$after|.delete_to=$delete_to|.action="delete-records-confirmed"' "$kafka_state"|atomic_json "$kafka_state";if (( $#>2 ));then "${@:3}";fi;restore_kafka;trap - EXIT INT TERM;kafka_status;;
 kafka:remove) restore_kafka;start_consumer;kafka_status;; kafka:status) kafka_status;;
 mysql:apply)
  export MYSQL_PWD="${MYSQL_PWD:?MYSQL_PWD required}";expire="$(mysqlq -e 'SELECT @@GLOBAL.binlog_expire_logs_seconds')";before_files="$(mysqlq -e 'SHOW BINARY LOGS'|awk '{print $1}'|jq -Rsc 'split("\n")|map(select(length>0))')";old="$(mysqlq -e 'SHOW BINARY LOG STATUS'|awk '{print $1}')";jq -n --argjson expire "$expire" --argjson before "$before_files" --arg old "$old" '{expire_before:$expire,before_files:$before,recorded_old:$old,action:"captured"}'|atomic_json "$mysql_state";register_cleanup "bash scenarios/scripts/fault-retention.sh remove mysql";trap 'restore_mysql' EXIT;trap 'signal_restore 130' INT;trap 'signal_restore 143' TERM
  mysqlq -e 'SET GLOBAL binlog_expire_logs_seconds=1;FLUSH BINARY LOGS;' >/dev/null;current="$(mysqlq -e 'SHOW BINARY LOG STATUS'|awk '{print $1}')";test "$old" != "$current"||{ echo 'binlog rotation did not advance current file' >&2;exit 1;};mysqlq -e "PURGE BINARY LOGS TO '$current'" >/dev/null
  "$wait_condition" 'recorded old MySQL binlog disappears' 30 0.2 bash -c 'SCENARIO_STATE_DIR="$1" "$2" status mysql|jq -e ".recorded_present==false" >/dev/null' _ "$state_dir" "$0"
  after_files="$(mysqlq -e 'SHOW BINARY LOGS'|awk '{print $1}'|jq -Rsc 'split("\n")|map(select(length>0))')";jq --arg current "$current" --argjson after "$after_files" '.current_after=$current|.after_files=$after|.action="safe-old-file-purge-confirmed"' "$mysql_state"|atomic_json "$mysql_state";if (( $#>2 ));then "${@:3}";fi;restore_mysql;trap - EXIT INT TERM;"$0" status mysql;;
 mysql:remove) restore_mysql;"$0" status mysql;;
 mysql:status) current="$(mysqlq -e 'SHOW BINARY LOG STATUS'|awk '{print $1}')";files="$(mysqlq -e 'SHOW BINARY LOGS'|awk '{print $1}'|jq -Rsc 'split("\n")|map(select(length>0))')";expire="$(mysqlq -e 'SELECT @@GLOBAL.binlog_expire_logs_seconds')";recorded=null;test ! -f "$mysql_state"||recorded="$(jq -r .recorded_old "$mysql_state")";jq -n --arg current "$current" --argjson files "$files" --argjson expire "$expire" --arg recorded "$recorded" '{target:"mysql",current_file:$current,files:$files,expire_seconds:$expire,recorded_file:$recorded,recorded_present:($files|index($recorded)!=null)}';;
 *) echo 'target must be kafka or mysql' >&2;exit 64;;
esac
