#!/usr/bin/env bash
set -euo pipefail

# Observable lifecycle: SNAPSHOTTING -> GATING -> VERIFYING -> CUTTING_OVER ->
# CUTOVER_COMMITTED -> COMPLETED; injected pre-boundary failures terminate FAILED.

compose=(docker compose -f infra/compose.yaml)
evidence_root="${M5_EVIDENCE_DIR:-evidence/m5/manual}"
case_dir=;active_request_pid=;retention_changed=false;mutation_pids=()
mkdir -p "$evidence_root"

mysql(){ MYSQL_PWD=rootpass command mysql --protocol=TCP -h127.0.0.1 -P3308 -N -B -uroot product_catalog -e "$1"; }
poll(){ local label="$1" timeout="$2" command="$3" start=$SECONDS;until eval "$command";do if ((SECONDS-start>=timeout));then die "timeout waiting for $label";fi;sleep 0.02;done; }
die(){ echo "ERROR: $*" >&2;collect_diagnostics;exit 1; }
uuid(){ uuidgen | tr '[:upper:]' '[:lower:]'; }
api(){ curl -fsS "$@"; }
wait_http(){ poll "$1" 180 "curl -fsS '$2' >/dev/null"; }
run_status(){ curl -sS "http://127.0.0.1:8083/internal/rebuild/runs/$1" 2>/dev/null | jq -r '.status // empty'; }
wait_phase(){ local run="$1" phase="$2" status start=$SECONDS;while true;do status="$(run_status "$run")";[[ "$status" == "$phase" ]] && return 0;if [[ "$status" == FAILED && "$phase" != FAILED ]];then die "rebuild $run failed before $phase";fi;if ((SECONDS-start>=180));then die "timeout waiting for rebuild $run phase $phase (last=$status)";fi;sleep 0.02;done; }
alias_index(){ curl -fsS http://127.0.0.1:9200/_alias/products_search,products_write | jq -er 'if length==1 then keys[0] else error("split aliases") end'; }
gate_json(){ mysql "SELECT JSON_OBJECT('closed',closed,'ownerRunId',BIN_TO_UUID(owner_run_id),'reason',reason) FROM product_write_gate WHERE singleton_id=1;" | jq .; }

collect_diagnostics(){ [[ -n "$case_dir" ]] || return 0;curl -sS http://127.0.0.1:8083/internal/pipeline/status >"$case_dir/failure-status.json" 2>/dev/null || true;curl -sS http://127.0.0.1:9200/_alias/products_search,products_write >"$case_dir/failure-aliases.json" 2>/dev/null || true;mysql "SELECT phase,partition_id,next_offset FROM rebuild_partition_offset ORDER BY run_id,phase,partition_id;" >"$case_dir/failure-offsets.json" 2>/dev/null || true;curl -sS http://127.0.0.1:8082/internal/rebuild/shadow/00000000-0000-0000-0000-000000000000 >"$case_dir/failure-shadow.json" 2>/dev/null || true;gate_json >"$case_dir/failure-gate.json" 2>/dev/null || true;"${compose[@]}" logs --no-color --tail=120 product-service search-sync-consumer consistency-verifier canal >"$case_dir/failure-services.log" 2>&1 || true; }
restore(){ curl -sS -X DELETE http://127.0.0.1:8083/internal/rebuild/failpoint >/dev/null 2>&1 || true;curl -sS -X DELETE http://127.0.0.1:8474/proxies/elasticsearch/toxics/m5-rebuild-latency >/dev/null 2>&1 || true;if $retention_changed;then "${compose[@]}" exec -T kafka /opt/kafka/bin/kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name product-search-revisions --alter --delete-config retention.ms,segment.ms,segment.bytes >/dev/null 2>&1 || true;retention_changed=false;fi; }
trap restore EXIT

ensure_stack(){ wait_http "product service" http://127.0.0.1:8081/actuator/health/liveness;wait_http "consumer" http://127.0.0.1:8082/actuator/health/liveness;wait_http "verifier" http://127.0.0.1:8083/actuator/health/liveness;wait_http "Elasticsearch" http://127.0.0.1:9200/_cluster/health; }
clean_task_state(){ restore;mysql "UPDATE product_write_gate SET closed=FALSE,owner_run_id=NULL,reason=NULL WHERE singleton_id=1; DELETE FROM canal_position_recovery; DELETE FROM canal_recovery_observation; DELETE FROM rebuild_partition_offset; DELETE FROM cdc_barrier; DELETE FROM rebuild_run; DELETE FROM sync_dlq_record; DELETE FROM sync_record_dlq; UPDATE pipeline_condition SET active=FALSE,cleared_at=CURRENT_TIMESTAMP(6) WHERE condition_key IN ('LOG_GAP','REBUILD_REQUIRED','REBUILD_IN_PROGRESS');" >/dev/null;local serving;serving="$(alias_index)";while read -r index;do [[ -z "$index" || "$index" == "$serving" ]] && continue;curl -fsS -X DELETE "http://127.0.0.1:9200/$index" >/dev/null;done < <(curl -fsS 'http://127.0.0.1:9200/_cat/indices/products_v3_*?h=index' || true); }
seed_catalog(){ if [[ "$(mysql 'SELECT COUNT(*) FROM products WHERE id BETWEEN 3000 AND 3400;')" != 401 ]];then for id in $(seq 3000 3400);do api -X POST http://127.0.0.1:8081/api/products -H 'Content-Type: application/json' -d "{\"id\":$id,\"sku\":\"SKU-$id\",\"name\":\"Product $id\",\"description\":\"M5 seed\",\"categoryId\":10,\"priceCents\":$id}" >/dev/null || true;done;fi;poll "seed projection" 180 "[[ \$(curl -fsS 'http://127.0.0.1:9200/products_write/_count'|jq -r .count) -ge 401 ]]";prepare_consistency; }
prepare_consistency(){ poll "primary lag zero" 180 "curl -fsS http://127.0.0.1:8083/internal/pipeline/status|jq -e '.kafkaLag==0 and .unresolvedDlq==0' >/dev/null";local report run;report="$(api -X POST http://127.0.0.1:8083/internal/reconciliation/runs -H 'Content-Type: application/json' -d '{"target":"products_write","pageSize":200}')";if [[ "$(jq -r .status <<<"$report")" == DIFF ]];then run="$(jq -r .runId <<<"$report")";api -X POST "http://127.0.0.1:8083/internal/reconciliation/runs/$run/repair" >/dev/null;api -X POST http://127.0.0.1:9200/products_write/_refresh >/dev/null;report="$(api -X POST http://127.0.0.1:8083/internal/reconciliation/runs -H 'Content-Type: application/json' -d '{"target":"products_write","pageSize":200}')";fi;jq -e '.status=="PASS" and .differenceCount==0' <<<"$report" >/dev/null || die "unable to establish consistent scenario baseline"; }
start_rebuild(){ local run="$1" reason="$2" output="$3";curl -sS -X POST http://127.0.0.1:8083/internal/rebuild/runs -H 'Content-Type: application/json' -d "{\"runId\":\"$run\",\"reason\":\"$reason\",\"topic\":\"product-search-revisions\",\"pageSize\":200}" >"$output" & active_request_pid=$!; }
wait_request(){ local allowed_failure="${1:-false}";set +e;wait "$active_request_pid";local rc=$?;set -e;active_request_pid=;if [[ "$allowed_failure" != true && $rc -ne 0 ]];then die "rebuild HTTP request failed";fi; }
snapshot_status(){ local run="$1";curl -fsS "http://127.0.0.1:8083/internal/rebuild/runs/$run" >"$case_dir/rebuild-status.json";gate_json >"$case_dir/gate.json";curl -fsS http://127.0.0.1:9200/_alias/products_search,products_write >"$case_dir/aliases.json";curl -fsS http://127.0.0.1:8083/internal/pipeline/status >"$case_dir/pipeline-status.json";curl -fsS http://127.0.0.1:8082/internal/dlq/count >"$case_dir/product-dlq.json";curl -fsS http://127.0.0.1:8082/internal/record-dlq/count >"$case_dir/record-dlq.json";mysql "SELECT JSON_OBJECT('source_watermark',source_watermark,'verificationRunId',BIN_TO_UUID(verification_run_id),'gateOwner',(SELECT BIN_TO_UUID(owner_run_id) FROM product_write_gate WHERE singleton_id=1),'aliasState',IF(alias_swapped,'NEW','OLD')) FROM rebuild_run WHERE run_id=UUID_TO_BIN('$run');" | jq . >"$case_dir/runtime-evidence.json"; }
assert_completed(){ local run="$1";wait_phase "$run" COMPLETED;snapshot_status "$run";curl -fsS http://127.0.0.1:8082/internal/rebuild/primary/status >"$case_dir/primary.json";jq -e '.status=="COMPLETED" and (.startOffsets|length)==3 and (.barrierOffsets|length)==3 and (.shadowOffsets|length)==3 and .verificationRunId!=null and .aliasState=="NEW"' "$case_dir/rebuild-status.json" >/dev/null || die "incomplete rebuild evidence";jq -e '.closed==0 and .ownerRunId==null' "$case_dir/gate.json" >/dev/null || die "gate remained closed";jq -e '.unresolved==0' "$case_dir/product-dlq.json" "$case_dir/record-dlq.json" >/dev/null || die "DLQ unresolved";jq -e '.state=="HEALTHY" and (.activeConditions|length)==0 and .kafkaLag==0 and .latestDifferenceCount==0' "$case_dir/pipeline-status.json" >/dev/null || die "completed rebuild is not healthy";jq -e '.running==true and .paused==false and .failureClass==null' "$case_dir/primary.json" >/dev/null || die "primary not actually resumed";jq -e 'length==1 and (to_entries[0].value.aliases.products_write.is_write_index==true) and (to_entries[0].value.aliases.products_search.filter.term.searchable==true)' "$case_dir/aliases.json" >/dev/null || die "alias topology/filter/write flag mismatch"; }
arm_latency(){ :; }

run_concurrent_mutations(){
  local deactivate_id="$1" create_id="$2";mutation_pids=()
  api -X PUT http://127.0.0.1:8081/api/categories/10 -H 'Content-Type: application/json' -d '{"name":"Concurrent Name"}' >"$case_dir/mutation-rename.json" & mutation_pids+=("$!")
  api -X PUT http://127.0.0.1:8081/api/products/1002/inventory -H 'Content-Type: application/json' -d '{"availableQuantity":77,"reservedQuantity":0}' >"$case_dir/mutation-inventory.json" & mutation_pids+=("$!")
  api -X DELETE "http://127.0.0.1:8081/api/products/$deactivate_id" >"$case_dir/mutation-deactivate.json" & mutation_pids+=("$!")
  api -X POST http://127.0.0.1:8081/api/products -H 'Content-Type: application/json' -d "{\"id\":$create_id,\"sku\":\"SKU-$create_id\",\"name\":\"Concurrent Create\",\"description\":\"during snapshot\",\"categoryId\":10,\"priceCents\":2001}" >"$case_dir/mutation-create.json" & mutation_pids+=("$!")
}
wait_concurrent_mutations(){ local pid;for pid in "${mutation_pids[@]}";do wait "$pid";done;mutation_pids=(); }

case_concurrent(){
  case_dir="$evidence_root/m5-concurrent-rebuild";mkdir -p "$case_dir";clean_task_state;seed_catalog;arm_latency
  local definition=scenarios/definitions/m5-concurrent-rebuild.json run deactivate_id create_id total code
  [[ "$(jq -r .scan_page_size "$definition")" == 200 ]] || die "scenario/runtime pageSize drift"
  run="$(uuid)";total="$(mysql 'SELECT COUNT(*) FROM product_search_revision;')"
  deactivate_id="$(mysql "SELECT id FROM products WHERE status='ACTIVE' AND id BETWEEN 3000 AND 3400 ORDER BY id LIMIT 1;")"
  create_id="$(mysql 'SELECT GREATEST(COALESCE(MAX(id),2000)+1,2001) FROM products;')"
  code="$(curl -sS -o "$case_dir/pre-gate-mutation.json" -w '%{http_code}' -X PUT http://127.0.0.1:8081/api/products/1001/price -H 'Content-Type: application/json' -d '{"priceCents":50000}')"
  [[ "$code" =~ ^2 ]] || die "writes blocked before gate"
  prepare_consistency
  start_rebuild "$run" NORMAL "$case_dir/start-response.json";wait_phase "$run" SNAPSHOTTING
  poll "settled partial snapshot page" 30 "count=\$(mysql \"SELECT source_count FROM rebuild_run WHERE run_id=UUID_TO_BIN('$run');\"); [[ \$count -gt 0 && \$count -lt $total ]]"
  mysql "SELECT JSON_OBJECT('source_count',source_count,'total',$total,'status',status) FROM rebuild_run WHERE run_id=UUID_TO_BIN('$run');"|jq . >"$case_dir/page-progress.json"
  run_concurrent_mutations "$deactivate_id" "$create_id";wait_phase "$run" GATING
  code="$(curl -sS -o "$case_dir/gated-mutation.json" -w '%{http_code}' -X PUT http://127.0.0.1:8081/api/products/1001/price -H 'Content-Type: application/json' -d '{"priceCents":50001}')";[[ "$code" == 503 ]] || die "write gate did not return HTTP 503"
  wait_concurrent_mutations;restore;wait_request;assert_completed "$run"
  code="$(curl -sS -o "$case_dir/retried-mutation.json" -w '%{http_code}' -X PUT http://127.0.0.1:8081/api/products/1001/price -H 'Content-Type: application/json' -d '{"priceCents":50001}')";[[ "$code" =~ ^2 ]] || die "write did not recover after gate"
  jq -n --arg run "$run" '{scenario:"m5-concurrent-rebuild",runId:$run,mutationsDuringSnapshot:true,probe:["SUCCESS",503,"SUCCESS"],gatingHttp:503,retry:"SUCCESS",terminal:"HEALTHY"}' >"$case_dir/result.json"
}
case_before(){ case_dir="$evidence_root/m5-rebuild-before-cutover-crash";mkdir -p "$case_dir";clean_task_state;seed_catalog;local old run generation;old="$(alias_index)";run="$(uuid)";api -X PUT http://127.0.0.1:8083/internal/rebuild/failpoint/BEFORE_ALIAS_SWITCH >"$case_dir/failpoint.json";start_rebuild "$run" NORMAL "$case_dir/start-response.json";wait_request true;wait_phase "$run" FAILED;restore;[[ "$(alias_index)" == "$old" ]] || die "before-boundary changed aliases";[[ "$(gate_json|jq -r .closed)" == 0 ]] || die "before-boundary gate closed";curl -fsS http://127.0.0.1:8082/internal/rebuild/primary/status >"$case_dir/primary.json";jq -e '.running==true and .paused==false' "$case_dir/primary.json" >/dev/null || die "primary remained paused";generation="$(mysql "SELECT generation_name FROM rebuild_run WHERE run_id=UUID_TO_BIN('$run');")";curl -fsS "http://127.0.0.1:9200/$generation" >"$case_dir/failed-generation.json";curl -fsS "http://127.0.0.1:8082/internal/rebuild/shadow/$run" >"$case_dir/failed-shadow.json";jq -e '.runId=="'$run'" and .running==false' "$case_dir/failed-shadow.json" >/dev/null || die "failed shadow evidence not retained";snapshot_status "$run";jq -e '.state=="REBUILD_REQUIRED" and (.activeConditions|index("REBUILD_REQUIRED"))!=null' "$case_dir/pipeline-status.json" >/dev/null || die "failed rebuild not reflected in pipeline state";jq -n --arg run "$run" --arg old "$old" --arg generation "$generation" '{scenario:"m5-rebuild-before-cutover-crash",runId:$run,authoritative:$old,failedGeneration:$generation,gate:"OPEN",primary:"RESUMED",pipeline:"REBUILD_REQUIRED",terminal:"FAILED"}' >"$case_dir/result.json"; }
case_after(){ case_dir="$evidence_root/m5-rebuild-after-cutover-crash";mkdir -p "$case_dir";clean_task_state;seed_catalog;local run promoted mutation_id;run="$(uuid)";api -X PUT http://127.0.0.1:8083/internal/rebuild/failpoint/AFTER_ALIAS_SWITCH_BEFORE_GATE_OPEN >"$case_dir/failpoint.json";start_rebuild "$run" NORMAL "$case_dir/start-response.json";wait_request true;wait_phase "$run" CUTOVER_COMMITTED;promoted="$(alias_index)";"${compose[@]}" restart consistency-verifier >"$case_dir/verifier-restart.log";wait_http "verifier recovery restart" http://127.0.0.1:8083/actuator/health;wait_phase "$run" COMPLETED;[[ "$(alias_index)" == "$promoted" ]] || die "forward recovery moved aliases back";assert_completed "$run";mutation_id="$(mysql 'SELECT GREATEST(COALESCE(MAX(id),4000)+1,4001) FROM products;')";api -X POST http://127.0.0.1:8081/api/products -H 'Content-Type: application/json' -d "{\"id\":$mutation_id,\"sku\":\"SKU-$mutation_id\",\"name\":\"Post restart\",\"description\":\"products_write proof\",\"categoryId\":10,\"priceCents\":7777}" >"$case_dir/post-restart-mutation.json";poll "post-restart mutation through products_write" 120 "curl -fsS http://127.0.0.1:9200/products_write/_doc/$mutation_id|jq -e '._source.product_id==$mutation_id' >/dev/null";api -X POST "http://127.0.0.1:9200/$promoted/_refresh" >/dev/null;api -X POST http://127.0.0.1:8083/internal/reconciliation/runs -H 'Content-Type: application/json' -d "{\"target\":\"$promoted\",\"pageSize\":200}" >"$case_dir/fresh-verification.json";jq -e '.status=="PASS" and .differenceCount==0' "$case_dir/fresh-verification.json" >/dev/null || die "post-recovery verification failed";jq -n --arg run "$run" --arg promoted "$promoted" '{scenario:"m5-rebuild-after-cutover-crash",runId:$run,authoritative:$promoted,recovery:"FORWARD_ONLY",primary:"RESUMED",postRestartMutation:"PRODUCTS_WRITE",freshPass:"PASS",terminal:"HEALTHY"}' >"$case_dir/result.json"; }

kafka_group_json(){ "${compose[@]}" exec -T kafka /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server kafka:9092 --group product-search-sync-v1 --describe 2>/dev/null | awk '$2=="product-search-revisions"&&$3~/^[0-9]+$/{printf "%s\"%s\":%s",sep,$3,$4;sep=","}END{print ""}' | sed '1s/^/{/' | sed '$s/$/}/' | jq -S .; }
kafka_beginning_json(){ "${compose[@]}" exec -T kafka /opt/kafka/bin/kafka-get-offsets.sh --bootstrap-server kafka:9092 --topic product-search-revisions --time -2 2>/dev/null | awk -F: '{printf "%s\"%s\":%s",sep,$2,$3;sep=","}END{print ""}' | sed '1s/^/{/' | sed '$s/$/}/' | jq -S .; }
force_retention_gap(){ local committed="$1" partition=2 cutoff;cutoff="$(( $(jq -r '."2"' <<<"$committed") + 1 ))";jq -n --argjson offset "$cutoff" '{version:1,partitions:[{topic:"product-search-revisions",partition:2,offset:$offset}]}' >"$case_dir/delete-records.json";"${compose[@]}" cp "$case_dir/delete-records.json" kafka:/tmp/m5-delete-records.json >/dev/null;"${compose[@]}" exec -T kafka /opt/kafka/bin/kafka-delete-records.sh --bootstrap-server kafka:9092 --offset-json-file /tmp/m5-delete-records.json >"$case_dir/delete-records-result.txt";poll "Kafka beginning beyond committed" 60 "[[ \$(kafka_beginning_json|jq -r '.\"2\"') -gt $((cutoff-1)) ]]";kafka_beginning_json >"$case_dir/beginning-after-retention.json"; }
case_kafka_gap(){ case_dir="$evidence_root/m5-kafka-gap-rebuild";mkdir -p "$case_dir";clean_task_state;seed_catalog;local committed;committed="$(kafka_group_json)";printf '%s\n' "$committed" >"$case_dir/committed-before-gap.json";"${compose[@]}" stop search-sync-consumer;"${compose[@]}" exec -T kafka /opt/kafka/bin/kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name product-search-revisions --alter --add-config retention.ms=100,segment.ms=100,segment.bytes=1048576 >/dev/null;retention_changed=true;for price in $(seq 60000 60120);do api -X PUT http://127.0.0.1:8081/api/products/1001/price -H 'Content-Type: application/json' -d "{\"priceCents\":$price}" >/dev/null;sleep 0.02;done;force_retention_gap "$committed";restore;"${compose[@]}" --profile m0-tools start search-sync-consumer;wait_http "consumer after gap" http://127.0.0.1:8082/actuator/health/liveness;poll "durable LOG_GAP" 120 "curl -fsS http://127.0.0.1:8083/internal/pipeline/status|jq -e '.state==\"REBUILD_REQUIRED\" and (.activeConditions|index(\"LOG_GAP\"))!=null' >/dev/null";curl -fsS http://127.0.0.1:8083/internal/pipeline/status >"$case_dir/gap-status.json";local run;run="$(uuid)";start_rebuild "$run" NORMAL "$case_dir/start-response.json";wait_request;assert_completed "$run";jq -e '.state=="HEALTHY" and (.activeConditions|length)==0' "$case_dir/pipeline-status.json" >/dev/null || die "Kafka gap did not recover";jq -n --arg run "$run" '{scenario:"m5-kafka-gap-rebuild",runId:$run,gap:"CONFIRMED",freshOStart:true,terminal:"HEALTHY"}' >"$case_dir/result.json"; }

case_mysql_gap(){ case_dir="$evidence_root/m5-mysql-binlog-gap-rebuild";mkdir -p "$case_dir";clean_task_state;seed_catalog;"${compose[@]}" stop canal >"$case_dir/canal-stop-before-purge.log" 2>&1 || true;"${compose[@]}" cp canal:/home/admin/canal-data/products/meta.dat "$case_dir/old-meta.dat" >/dev/null;bash scenarios/scripts/decode-canal-meta.sh "$case_dir/old-meta.dat" >"$case_dir/old-meta.json";local journal position current run;journal="$(jq -r .journal "$case_dir/old-meta.json")";position="$(jq -r .position "$case_dir/old-meta.json")";mysql "FLUSH BINARY LOGS;" >/dev/null;current="$(mysql 'SHOW BINARY LOG STATUS;'|awk '{print $1}')";mysql "PURGE BINARY LOGS TO '$current';" >/dev/null;! mysql 'SHOW BINARY LOGS;'|awk '{print $1}'|grep -Fxq "$journal" || die "failed to purge old cursor journal";api -X PUT http://127.0.0.1:8083/internal/pipeline/conditions/LOG_GAP -H 'Content-Type: application/json' -d "{\"journal\":\"$journal\",\"position\":$position}" >"$case_dir/log-gap.json";run="$(uuid)";api -X POST http://127.0.0.1:8083/internal/rebuild/runs -H 'Content-Type: application/json' -d "{\"runId\":\"$run\",\"reason\":\"MYSQL_BINLOG_GAP\",\"topic\":\"product-search-revisions\",\"pageSize\":200}" >"$case_dir/recovery-required.json";api -X POST "http://127.0.0.1:8083/internal/rebuild/runs/$run/canal-recovery/start" >"$case_dir/recovery-started.json";bash scenarios/scripts/reset-canal-position.sh "$run" "$case_dir/canal-recovery";assert_completed "$run";jq -n --arg run "$run" '{scenario:"m5-mysql-binlog-gap-rebuild",runId:$run,cursorRecovery:"VERIFIED",resetModeBoots:1,normalSentinels:"EXACT_NEXT",terminal:"HEALTHY"}' >"$case_dir/result.json"; }

ensure_stack
default_cases="case_concurrent case_before case_after case_kafka_gap case_mysql_gap"
read -r -a cases <<<"${M5_CASES:-$default_cases}"
for scenario_case in "${cases[@]}";do echo "==> ${scenario_case#case_}";"$scenario_case";done
jq -s 'sort_by(.scenario)' "$evidence_root"/*/result.json >"$evidence_root/terminal-classifications.json"
echo "M5 rebuild matrix passed: $evidence_root"
